# -- Configuración base del sitio --
theme = "congo"
baseURL = "https://blog-cmj.pages.dev/"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[sitemap]
  changeFreq = "daily"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false

[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "date"
    weight = 10

[caches]
  [caches.images]
    dir = ":cacheDir/images"
