# -- Configuración base del sitio --
theme = "hextra"
baseURL = "https://blog-cmj.pages.dev/"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true
summaryLength = 70

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  grupo = "grupos" # <-- Añadido para que coincida con tu layout

[sitemap]
  changeFreq = "weekly"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.extensions.typographer]
  disable = false
[markup.highlight]
  noClasses = false

[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "date"
    weight = 10

[caches.images]
  dir = ":cacheDir/images"

# -- Configuración de Idiomas --
# Al no especificar contentDir, Hugo usará la raíz /content/ para ambos.
# Para el idioma secundario (en), deberás usar el sufijo de archivo, ej: primer-post.en.md
[languages]
  [languages.es]
    label = "Español"
    weight = 1
  [languages.en]
    label = "English"
    weight = 2