# -- Parámetros del tema Blowfish --
# Ref: https://blowfish.page/docs/configuration/

colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["posts"]

disableImageOptimization = false
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showAuthor = false
  showHero = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  showTaxonomies = true
  showWordCount = false
  sharingLinks = []

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  groupByYear = false
  cardView = false
