# -- Parámetros del tema Hextra --
# Ref: https://github.com/imfing/hextra

[navbar]
  displayTitle = true
  displayLogo = false

externalLinkDecoration = true
displayUpdatedDate = true
displayUpdatedAuthor = false

[theme]
  default = "system"
  displayToggle = true

[search]
  enable = true
  type = "flexsearch"
  [search.flexsearch]
    index = "content"
    tokenize = "forward"

[toc]
  displayTags = true

[blog.list]
  displayTags = true
  sortBy = "date"
  sortOrder = "desc"
  pagerSize = 10

[blog.article]
  displayPagination = true

[archives]
  section = "posts"
  dateFormat = "2 Jan"

[highlight.copy]
  enable = true
  display = "hover"

[page]
  width = "normal"

[imageZoom]
  enable = true

[footer]
  displayCopyright = true
  displayPoweredBy = false

[comments]
  enable = false
